### ISSUE TITLE
알고리즘 풀이 #2

### ISSUE THREAD

**Issue by gihop** [Boost-Up-AI/Group-Activity#11]
👨‍💻 알고리즘 코드 리뷰 (algorithm label)

다음 문제를 선정했습니다!

구슬 탈출4
https://www.acmicpc.net/problem/15653

**Comment by ebbunnim** [comment]
시리즈가 4까지 있나요....? 무서운 문제군요.... ㅎㅎ

**Comment by ebbunnim** [comment]
https://github.com/ebbunnim/Algorithm/blob/d3674b24ac5df21acd7599451fbf6a260c8dd0bd/%EB%B0%B1%EC%A4%80/15653_%EA%B5%AC%EC%8A%AC%ED%83%88%EC%B6%9C4.py

**Comment by gihop** [comment]
https://github.com/gihop/AlgorithmStudy/blob/master/%EB%B6%80%EC%8A%A4%ED%8A%B8%EC%BA%A0%ED%94%84/python/%EA%B5%AC%EC%8A%AC%ED%83%88%EC%B6%9C4_15653.py
