### ISSUE TITLE
[Day13] CNN 코드

### ISSUE THREAD

**Issue by nureesong** [Boost-Up-AI/Group-Activity#13]
## 📚 링크, 서적 공유

- 최성준 교수님 CNN 과제 코드를 도식화한 그림입니다.
- 각 layer 별로 parameter 개수를 직접 계산해보시고
- summary 한 결과와 맞는지 비교해보시면 좋을 것 같습니다.

![Day13_CNN모델](https://user-images.githubusercontent.com/76163168/106711652-297b9280-663b-11eb-9c50-8a887106f87f.jpg)

**Comment by ebbunnim** [comment]
누리님 정말 감사합니다.. ㅠㅠ 짱짱
