### ISSUE TITLE
알고리즘 풀이 #3

### ISSUE THREAD

**Issue by gihop** [Boost-Up-AI/Group-Activity#14]
👨‍💻 알고리즘 코드 리뷰 (algorithm label)

BFS 3번째 문제
- https://www.acmicpc.net/problem/1194
- 비트마스킹이라는 개념을 참고하시면 좋을 것 같습니다!

DFS
- https://www.acmicpc.net/problem/1987
- https://www.acmicpc.net/problem/2668
- https://www.acmicpc.net/problem/9466
  - 시간 초과 주의💢

Further Question
- https://www.acmicpc.net/problem/1981
- 이분탐색 개념을 잡으셔도 좋을 것 같아서요!(안해도 됨)

모두 설 연휴 잘보내세요~!

**Comment by nureesong** [comment]
지호님 저는 망했습니다..ㅋㅋㅋㅋ 노는 건 왜 질리지가 않는지ㅎㅎ
할 수 있는데까지 해볼게요!!

**Comment by ebbunnim** [comment]
1194번-https://bit.ly/3jBoX3k
1987번-https://bit.ly/3tOZHLu
2668번-https://bit.ly/3rMo76L
9466번-https://bit.ly/372cXCR
1981번-https://bit.ly/3jL2xwv

**Comment by nureesong** [comment]
BFS 어렵습니다... 갈 길이 멀군요ㅜㅜ
DFS
1987번 (시간초과) - https://github.com/nureesong/BaekJoon/blob/master/Alphabet_1987_final.py
2668번 - https://github.com/nureesong/BaekJoon/blob/master/SelectNum_2668_github.py
9466번 (시간초과) - https://github.com/nureesong/BaekJoon/blob/master/TermProject_9466_timeout_final.py

**Comment by gihop** [comment]
ㅋㅋㅋㅋㅋㅋ누리님은 좀 노셔도 되는데 저는 왜 놀았을까요..
1194번 - https://bit.ly/3tWShpD
1987번 - https://bit.ly/3b8C6Nk
2668번 - https://bit.ly/3pf4NNK
9466번 - https://bit.ly/2Npsc1G

**Comment by DongHyunSuh** [comment]
1194번 - 실패
1987번 - https://bit.ly/3s0rvuV
2668번 - https://bit.ly/3ql4LVO
9466번 - 실패
이번 알고리즘 문제 난이도가...너무 어렵습니다...
