### ISSUE TITLE
[책 추천] 동현님 들어오세요ㅋㅋㅋ

### ISSUE THREAD

**Issue by nureesong** [Boost-Up-AI/Group-Activity#17]
## 📚 서적 공유
- 대학원생 때 알았더라면 좋았을 것들 (https://gradschoolstory.net/)
- 대학원 진학을 고민 중이신 동현님께 도움이 될 것 같아 추천합니다. \
박사님들의 블로그 글을 엮어 출간된 책이고 저도 추천받아서 석사 1,3학기 때 두 번 읽었습니다.
그리고 2명의 대학원생 친구들에게 빌려주고 독후감을 남기도록 강요했습니다ㅋㅋㅋ
독후감도 같이 공유하면 좋을 거 같아 책을 빌려드리고 싶은데 오프라인 모임이 가능할지 모르겠네요ㅠㅠ
나중에라도 원하시면 빌려드리겠습니다! 궁금한 거 있으시면 편하게 연락해주세요ㅎㅎ

**Comment by DongHyunSuh** [comment]
이렇게 좋은 자료를 공유해주시면 너무 감사드립니다...
꼭 읽어보고 부스트캠프가 끝나기 전에 목표하고자 하는 진로를 결정하도록 하겠습니다.
추후 대학원 관련해서 궁금한거 있으면 질문 드리도록 하겠습니다!
진심으로 감사드립니다 :)
