### ISSUE TITLE
[Day6] 무어-펜로즈 역행렬 (강의록 p.28)

### ISSUE THREAD

**Issue by nureesong** [Boost-Up-AI/Group-Activity#4]
##  👍 꿀팁 공유

 - 오늘 피어세션에서 다룬 유사역행렬에 대해 다시 생각해봤는데, 
 - 제가 이해한 방법이 도움이 될까 해서 정리한 노트를 첨부합니다.

![moore-pensore](https://user-images.githubusercontent.com/76163168/105824419-a8e8e080-6001-11eb-95de-88dd8b136237.PNG)

참고: https://en.wikipedia.org/wiki/Invertible_matrix

**Comment by ebbunnim** [comment]
완전 깔끔한 정리.... 감사합니다 누리님 ㅎㅎ

**Comment by gihop** [comment]
오... 감사합니다!! 이해 됐습니다!

**Comment by DongHyunSuh** [comment]
n<m인 경우에는 Ax=b가 아니라 x=(A^+)b로 시작하는거였군요...
누리님 덕분에 이해됐습니다. 감사합니다!!
