### ISSUE TITLE
[Day7] Further Question

### ISSUE THREAD

**Issue by nureesong** [Boost-Up-AI/Group-Activity#5]
##  👍 꿀팁 공유

 - 자주 사용되는 L2norm, 벡터, 행렬에 대한 연산입니다. 
   2,3차원 정도로 고정하여 시그마 표현을 전개해보시면 이해하는데 도움이 되실 겁니다.
 - Further question 도 2차원으로 예를 들어서 미분했는데 이해 안되는 부분 있으시면 편하게 질문해주세요!
 
 
[Day7_Further_Question_송누리.pdf](https://github.com/Boost-Up-AI/Group-Activity/files/5873215/Day7_Further_Question_.pdf)

**Comment by gihop** [comment]
와...그저 빛.......감사합니다..ㅠㅠ

**Comment by DongHyunSuh** [comment]
와...진짜 깔끔한 정리 너무 감사합니다!!
