### ISSUE TITLE
fork lecture-note-python-basics-for-ai

### ISSUE THREAD

**Issue by ebbunnim** [Boost-Up-AI/Group-Activity#6]
## 📚 링크, 서적 공유 (recommend label)

 - 실습 코드들이 들어있는 repo fork해두었습니다.

**Comment by nureesong** [comment]
지영님 제가 깃허브를 처음 써봐서 fork가 뭔지 잘 모르겠어요ㅎㅎ피어세션 때 설명해주시면 감사하겠습니다!

**Comment by ebbunnim** [comment]
넵 ㅎㅎ 참고 url 우선 추가해 두겠습니다!
https://www.secmem.org/blog/2019/04/10/git_pr/
