### ISSUE TITLE
Numpy와 Pandas의 axis 비교

### ISSUE THREAD

**Issue by DongHyunSuh** [Boost-Up-AI/Group-Activity#7]
오늘 강의 듣다가 df.drop('column name', axis = n) 관련해서 헷갈리는 부분 공유합니다.

Numpy에서는 새로운 axis가 추가되면 기존 axis들은 +1 되는 방식이었습니다.
예시) (row=0, col=1) -> (channel=0, row=1, col=2)

그런데 오늘 강의에서는 df.drop('column name', axis = n) 하면 해당 axis의 데이터가 지워지는게 아니라,
axis를 기준으로 데이터가 지워졌습니다.
예시) df.drop('column name', axis = 1) 하면 column name의 열 데이터 삭제

그래서 Numpy와 Pandas의 axis가 다른지 찾아보다가 잘 설명되어 있는 url 공유합니다.
결론적으로는 Numpy는 axis 전체를, Pandas는 axis를 기준으로 데이터를 표현하는 것 같습니다.
![image](https://user-images.githubusercontent.com/77680169/105939221-1ba69a00-609c-11eb-9af2-f1a2401c1741.png)

url: https://stackoverflow.com/questions/25773245/ambiguity-in-pandas-dataframe-numpy-array-axis-definition

**Comment by nureesong** [comment]
저도 axis가 헷갈렸는데 감사합니다:)

**Comment by gihop** [comment]
강의 들으면서 의아했던 부분이었는데..감사합니다!
