### ISSUE TITLE
[복습]  행렬곱(@)과 np.inner

### ISSUE THREAD

**Issue by nureesong** [Boost-Up-AI/Group-Activity#9]
##  피어세션 1월 28일 (목)

- 지호님 아까 말씀하셨던 부분이 저도 명확하지 않아서 몇 가지 시도해봤습니다. 
- 넘파이 배열의 차원에 따라 결과가 달라지니 대괄호 개수에 유의해야 할 것 같아요!
- 넘파이 아직 어렵습니다ㅜㅜ

---------------------------------------------------------------------
import numpy as np   

np.array([1,2]) @ np.array([2,3])     # shape : (2,) @ (2,)     
#결과: 8    1차원 배열끼리의 행렬곱 = 두 벡터의 내적(dot)

np.array([[1,2]]) @ np.array([[2,3]])     # shape : (1,2) @ (1,2) 
#Error  ->  2차원 배열의 행,열 개수가 안 맞아서 행렬곱 불가능

np.inner(np.array([[1,2]]), np.array([[2,3]]))    # shape : (1,2) @ (1,2).T     
#array([[8]])    np.inner로 해야 계산 가능

np.array([1,2]) @ np.array([[2],[3]])     # shape : (2,) @ (2,1)
#array([8])

np.array([[1,2],[0,1]]) @ np.array([2,3])     # shape : (2,2) @ (2,) 
#array([8, 3])
#[1,2] @ [2,3] = 8 
#[0,1] @ [2,3] = 3

**Comment by gihop** [comment]
기준이 어렵네요ㅜㅜㅜ 설명해주셔서 감사합니다!!!
